---
- hosts: arista
  connection: local
  tasks:
    - eos_config:
        lines:
          - no switchport
          - ip address 172.16.1.1/24
        parents: interface Ethernet1
        provider: "{{login_info_eos}}"
